# Generated by Django 5.0.1 on 2024-02-22 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=144)),
                ('telefono_ciudad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email_ciudad', models.EmailField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Niveltitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=144)),
            ],
            options={
                'verbose_name_plural': 'Niveltitulo',
            },
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleo', models.CharField(max_length=144)),
                ('descripcion_empleo', models.TextField(blank=True, null=True)),
                ('fecha_empleo', models.DateField(default=django.utils.timezone.now)),
                ('area_empleo', models.CharField(max_length=200)),
                ('modalidad_empleo', models.CharField(max_length=200)),
                ('tiempo_empleo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('id_ciudad_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad', to='app.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_postulante', models.CharField(max_length=144)),
                ('apellido_postulante', models.CharField(max_length=144)),
                ('genero_postulante', models.CharField(max_length=144)),
                ('edad_postulante', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('direccion_postulante', models.CharField(max_length=200)),
                ('email_postulante', models.EmailField(max_length=150)),
                ('telefono_postulante', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('ciudad_postulante', models.CharField(max_length=144)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_postulado', models.CharField(max_length=144)),
                ('fecha_postulado', models.DateField(default=django.utils.timezone.now)),
                ('id_empleo_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulados', to='app.empleo')),
                ('id_postulados_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulado', to='app.postulante')),
            ],
            options={
                'verbose_name_plural': 'Postulados',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_exp', models.CharField(max_length=255)),
                ('empresa_exp', models.CharField(max_length=255)),
                ('pais_exp', models.CharField(max_length=255)),
                ('area_exo', models.CharField(max_length=255)),
                ('finicio_exp', models.DateField()),
                ('ffinal_exp', models.DateField(blank=True, null=True)),
                ('descripcion_exp', models.TextField(blank=True, null=True)),
                ('id_experiencia_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulanteexp', to='app.postulante')),
            ],
            options={
                'verbose_name_plural': 'Experiencia',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_edu', models.CharField(max_length=255)),
                ('pais_edu', models.CharField(max_length=255)),
                ('institucion_edu', models.CharField(max_length=255)),
                ('estado_edu', models.CharField(max_length=255)),
                ('descripcion_edu', models.TextField(blank=True, null=True)),
                ('nivel_edu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivelid', to='app.niveltitulo')),
                ('id_educacion_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulanteedu', to='app.postulante')),
            ],
            options={
                'verbose_name_plural': 'Educacion',
            },
        ),
        migrations.CreateModel(
            name='Detallepostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_laboral', models.TextField(blank=True, null=True)),
                ('idioma_laboral', models.CharField(blank=True, max_length=255, null=True)),
                ('id_postulante_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to='app.postulante')),
            ],
        ),
    ]
