# Generated by Django 5.0.2 on 2024-02-27 22:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=144)),
                ('telefono_ciudad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email_ciudad', models.EmailField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Niveltitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=144)),
            ],
            options={
                'verbose_name_plural': 'Niveltitulo',
            },
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_edu', models.CharField(max_length=255)),
                ('pais_edu', models.CharField(max_length=255)),
                ('institucion_edu', models.CharField(max_length=255)),
                ('nivel_edu', models.CharField(max_length=255)),
                ('estado_edu', models.CharField(max_length=255)),
                ('descripcion_edu', models.TextField(blank=True, null=True)),
                ('id_educacion_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion_postulante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Educacion',
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleo', models.CharField(max_length=144)),
                ('descripcion_empleo', models.TextField(blank=True, null=True)),
                ('fecha_empleo', models.DateField(default=django.utils.timezone.now)),
                ('area_empleo', models.CharField(max_length=200)),
                ('modalidad_empleo', models.CharField(max_length=200)),
                ('tiempo_empleo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('anos_minimos_experiencia', models.IntegerField(blank=True, null=True)),
                ('id_ciudad_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleo_ciudad', to='app.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('postulante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_postulante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experiencia',
            },
        ),
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_postulado', models.CharField(max_length=144)),
                ('fecha_postulado', models.DateField(default=django.utils.timezone.now)),
                ('id_empleo_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulados', to='app.empleo')),
                ('id_postulados_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Postulados',
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144, null=True)),
                ('apellido', models.CharField(max_length=144, null=True)),
                ('genero', models.CharField(max_length=144, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('ciudad', models.CharField(max_length=144, null=True)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='media/curriculums')),
                ('usuario_postulante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_postulante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
