# Generated by Django 5.0.2 on 2024-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ciudad_niveltitulo_alter_publicacion_options_empleo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='curriculum',
            field=models.FileField(blank=True, upload_to='media/curriculums'),
        ),
    ]
