# Generated by Django 5.0.2 on 2024-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ciudad_niveltitulo_alter_publicacion_options_empleo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='User',
            new_name='usuario_postulante',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombre',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
