# Generated by Django 5.0.1 on 2024-02-23 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ciudad_niveltitulo_alter_publicacion_options_empleo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='id_experiencia_fk',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='postulante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='app.postulante'),
        ),
    ]
