# Generated by Django 5.0.2 on 2024-02-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ciudad_niveltitulo_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='id_educacion_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion_postulante', to='app.postulante'),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='id_ciudad_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad', to='app.ciudad'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='postulante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_postulante', to='app.postulante'),
        ),
        migrations.AlterField(
            model_name='postulados',
            name='id_postulados_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulado', to='app.postulante'),
        ),
    ]
