# Generated by Django 5.0.2 on 2024-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulados',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
