# Generated by Django 5.0.1 on 2024-02-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_area_exo_experiencia_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='anos_minimos_experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
