# Generated by Django 5.0.2 on 2024-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_postulados_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
