# Generated by Django 5.0.2 on 2024-02-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_empleo_anos_minimos_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='telefono_postulante',
            field=models.CharField(max_length=10),
        ),
    ]
