# Generated by Django 5.0.2 on 2024-03-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_empleo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='titulo',
            field=models.FileField(blank=True, null=True, upload_to='media/titulos'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='media/certificados'),
        ),
    ]
