# Generated by Django 5.0.2 on 2024-02-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_postulante_telefono_postulante'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='total_experiencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='edad_postulante',
            field=models.IntegerField(max_length=2),
        ),
    ]
