# Generated by Django 5.0.2 on 2024-03-12 02:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_empleo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('empleo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistaempleo', to='app.empleo')),
                ('postulante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistapostulante', to='app.postulante')),
            ],
        ),
    ]
