# Generated by Django 5.0.2 on 2024-03-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_educacion_titulo_experiencia_certificado'),
        ('app', '0007_entrevista'),
    ]

    operations = [
    ]
