# Generated by Django 5.0.1 on 2024-02-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_personal_delete_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name_plural': 'Personal'},
        ),
    ]
